#!/usr/bin/env bash
set -euo pipefail

# Cosmos roadmap milestone 0.2 — auto-detect installed Steam games and turn them
# into launcher configs that install_cosmos.command builds into .app bundles.
#
# It scans the Steam libraries inside the Wine prefix (libraryfolders.vdf +
# appmanifest_*.acf), then writes one generated config per installed game into
# cosmos_configs/ named "steam-<appid>-<slug>.conf". Games that already have a
# hand-curated config (matched by Steam App ID) are skipped so curated presets win.
#
# Per-game extras (graphics backend, extra env vars, launch args) can be attached
# to an auto-detected game by dropping a "cosmos_configs/overrides/<appid>.env"
# file with simple KEY=VALUE lines. Those are merged into the generated config and
# survive refreshes. See cosmos_configs/overrides/README.md.
#
# Each game's icon is built from Steam's locally-cached artwork (appcache/
# librarycache) into cosmos_configs/icons/steam-<appid>.icns and referenced from
# the generated config via ICON_PATH. This needs macOS (sips + iconutil); when the
# tools or the artwork are missing the launcher keeps the default Cosmos icon.
#
# Usage:
#   detect_steam_games.command            # default: refresh generated configs
#   detect_steam_games.command --list     # print detected games, write nothing
#   detect_steam_games.command --write     # write/refresh generated configs (default)
#   detect_steam_games.command --install   # write configs, then build all launchers

SCRIPT_DIR="${SCRIPT_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)}"
CONFIGS_DIR="${COSMOS_CONFIGS_DIR:-${SCRIPT_DIR}/cosmos_configs}"
# User-authored per-game overrides keyed by Steam App ID (overrides/<appid>.env).
# These are merged into the generated config so extra env / backend / launch args
# survive a refresh (which otherwise overwrites the auto-generated configs).
OVERRIDES_DIR="${COSMOS_OVERRIDES_DIR:-${CONFIGS_DIR}/overrides}"
WINEPREFIX="${WINEPREFIX:-$HOME/.wine-steam-11}"

# Per-game .icns icons are converted from Steam's locally-cached artwork into this
# directory and referenced from the generated configs via ICON_PATH. Set
# COSMOS_SKIP_ICONS=1 to skip icon generation (e.g. on a fresh prefix where Steam
# has not downloaded library art yet). COSMOS_ICON_TOOL overrides the converter.
ICONS_DIR="${COSMOS_ICONS_DIR:-${CONFIGS_DIR}/icons}"
# Locate the icon converter in both the repo layout (scripts/) and the flattened
# layout used inside an installed app bundle's Resources.
if [[ -n "${COSMOS_ICON_TOOL:-}" ]]; then
  ICON_TOOL="${COSMOS_ICON_TOOL}"
elif [[ -x "${SCRIPT_DIR}/scripts/make_app_icon.command" ]]; then
  ICON_TOOL="${SCRIPT_DIR}/scripts/make_app_icon.command"
else
  ICON_TOOL="${SCRIPT_DIR}/make_app_icon.command"
fi
STEAM_DIR=""

AUTO_HEADER="# AUTO-GENERATED by detect_steam_games.command. Re-run to refresh; edits will be overwritten."
MODE="write"

# Steam App IDs that are tools/runtimes/redistributables rather than games.
IGNORED_APPIDS=" 228980 1070560 1391110 1628350 1493710 "

log() { printf "\n==> %s\n" "$1"; }
die() { printf "Error: %s\n" "$1" >&2; exit 1; }

usage() {
  cat <<'EOF'
Auto-detect installed Steam games and turn them into Cosmos launcher configs.

Usage: detect_steam_games.command [--list|--write|--install]
  --list      Print detected installed Steam games and exit (writes nothing).
  --write     (default) Write/refresh generated configs in cosmos_configs/.
  --install   Write configs, then run install_cosmos.command to build launchers.
EOF
}

parse_arguments() {
  case "${1:-}" in
    ""|--write) MODE="write" ;;
    --list) MODE="list" ;;
    --install) MODE="install" ;;
    --help|-h) usage; exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
  (($# <= 1)) || die "This script accepts at most one argument."
}

# True for Steam entries that are tools/runtimes rather than games, so they don't
# become junk launchers (e.g. Steamworks Common Redistributables, Proton, runtimes).
is_ignored_app() {
  local appid="$1" name="$2"
  [[ "${IGNORED_APPIDS}" == *" ${appid} "* ]] && return 0
  printf '%s' "${name}" | grep -Eqi \
    'steamworks common redistributables|steam linux runtime|^proton( |$|-)|^steamvr$' && return 0
  return 1
}

slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

# Sanitize a Steam name into something safe for an APP_NAME / .app directory:
# '/' and ':' are not valid in macOS file names, and characters that are special
# inside a double-quoted shell string are escaped because the generated config is
# sourced by install_cosmos.command.
safe_app_name() {
  local name="$1"
  name="${name//\\/}"          # drop backslashes
  name="${name//\//-}"         # '/' not allowed in file names
  name="${name//:/ -}"         # ':' shows as '/' in Finder
  name="${name//\"/}"          # drop double quotes (would close the string)
  name="${name//\$/}"          # drop '$' (no expansion when sourced)
  name="${name//\`/}"          # drop backticks (no command substitution)
  printf '%s' "${name}"
}

# Convert a Windows path from libraryfolders.vdf to a path inside the prefix via
# the prefix's dosdevices drive symlinks (c: -> drive_c, z: -> /, etc.).
win_to_unix() {
  local p="$1"
  p="${p//\\//}"                       # backslashes -> forward slashes
  local drive rest
  drive="$(printf '%s' "${p:0:1}" | tr '[:upper:]' '[:lower:]')"
  rest="${p:2}"                        # strip "X:"
  printf '%s/dosdevices/%s:%s' "${WINEPREFIX}" "${drive}" "${rest}"
}

find_steam_dir() {
  local a="${WINEPREFIX}/drive_c/Program Files (x86)/Steam"
  local b="${WINEPREFIX}/drive_c/Program Files/Steam"
  if [[ -d "${a}" ]]; then printf '%s' "${a}"; elif [[ -d "${b}" ]]; then printf '%s' "${b}"; fi
}

# Print the steamapps directory for every Steam library (newline separated, deduped).
collect_steamapps_dirs() {
  local steam_dir="$1"
  local vdf="${steam_dir}/steamapps/libraryfolders.vdf"
  {
    printf '%s\n' "${steam_dir}/steamapps"
    if [[ -f "${vdf}" ]]; then
      local path
      while IFS= read -r path; do
        [[ -n "${path}" ]] || continue
        printf '%s/steamapps\n' "$(win_to_unix "${path}")"
      done < <(awk -F'"' '$2=="path"{print $4}' "${vdf}")
    fi
  } | awk '!seen[$0]++'
}

# Record Steam App IDs that already have a hand-curated (non auto-generated) config.
curated_appids=""
collect_curated_appids() {
  local cfg aid
  shopt -s nullglob
  for cfg in "${CONFIGS_DIR}"/*.conf; do
    grep -q 'AUTO-GENERATED by detect_steam_games' "${cfg}" && continue
    aid="$(sed -n 's/^STEAM_GAME_ID="\{0,1\}\([0-9][0-9]*\)"\{0,1\}.*/\1/p' "${cfg}" | head -n1)"
    [[ -n "${aid}" ]] && curated_appids+=" ${aid} "
  done
  shopt -u nullglob
}

is_curated() { [[ "${curated_appids}" == *" $1 "* ]]; }

remove_stale_generated() {
  local cfg
  shopt -s nullglob
  for cfg in "${CONFIGS_DIR}"/steam-*.conf; do
    grep -q 'AUTO-GENERATED by detect_steam_games' "${cfg}" && rm -f "${cfg}"
  done
  shopt -u nullglob
}

# Keys that install_cosmos.command consumes at build time only (they are not
# runtime env, so they must NOT go into RUN_ENV_NAMES). APP_NAME / BUNDLE_ID /
# STEAM_GAME_ID are managed by this script and ignored if an override sets them.
OVERRIDE_RESERVED_KEYS=" STEAM_GAME_ID APP_NAME BUNDLE_ID "
OVERRIDE_BUILD_KEYS=" ICON_PATH APP_VERSION LS_MINIMUM_SYSTEM_VERSION "

# Populate the OVERRIDE_* globals from cosmos_configs/overrides/<appid>.env:
#   OVERRIDE_NAMES        runtime env var names (added to RUN_ENV_NAMES)
#   OVERRIDE_LINES        runtime assignment lines
#   OVERRIDE_BUILD_LINES  build-time assignment lines (e.g. a custom ICON_PATH)
# Only well-formed KEY=VALUE lines with an upper-snake-case KEY are accepted;
# everything else (comments, blanks, stray shell) is ignored so the override file
# cannot smuggle arbitrary commands into the sourced config.
# (Globals + manual parallel arrays keep this compatible with macOS bash 3.2,
# which has no namerefs.)
OVERRIDE_NAMES=()
OVERRIDE_LINES=()
OVERRIDE_BUILD_LINES=()
read_overrides() {
  local appid="$1"
  OVERRIDE_NAMES=()
  OVERRIDE_LINES=()
  OVERRIDE_BUILD_LINES=()
  local override_file="${OVERRIDES_DIR}/${appid}.env"
  [[ -f "${override_file}" ]] || return 0

  local line key existing seen
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%$'\r'}"                       # tolerate CRLF
    [[ "${line}" =~ ^[[:space:]]*(#|$) ]] && continue
    [[ "${line}" == *=* ]] || continue
    key="${line%%=*}"
    key="${key//[[:space:]]/}"
    [[ "${key}" =~ ^[A-Z][A-Z0-9_]*$ ]] || continue
    [[ "${OVERRIDE_RESERVED_KEYS}" == *" ${key} "* ]] && continue
    if [[ "${OVERRIDE_BUILD_KEYS}" == *" ${key} "* ]]; then
      OVERRIDE_BUILD_LINES+=("${key}=${line#*=}")
      continue
    fi
    # Skip a runtime key already collected so RUN_ENV_NAMES and the assignments
    # stay 1:1.
    seen=0
    for existing in ${OVERRIDE_NAMES[@]+"${OVERRIDE_NAMES[@]}"}; do
      [[ "${existing}" == "${key}" ]] && { seen=1; break; }
    done
    (( seen )) && continue
    OVERRIDE_NAMES+=("${key}")
    OVERRIDE_LINES+=("${key}=${line#*=}")
  done < "${override_file}"
}

# Echo the best locally-cached Steam artwork file for an App ID, or nothing.
# Preference order favors a square clienticon, then portrait/landscape capsules
# (which get centre-cropped to square by the converter). Both the historical flat
# naming and the newer per-appid subfolder layout are probed.
find_icon_source() {
  local appid="$1" steam_dir="$2"
  local lc="${steam_dir}/appcache/librarycache"
  local candidate
  for candidate in \
    "${lc}/${appid}_icon.jpg" \
    "${lc}/${appid}/icon.jpg" \
    "${lc}/${appid}_library_600x900.jpg" \
    "${lc}/${appid}/library_600x900.jpg" \
    "${lc}/${appid}_header.jpg" \
    "${lc}/${appid}/header.jpg" \
    "${lc}/${appid}_logo.png" \
    "${lc}/${appid}/logo.png"; do
    [[ -f "${candidate}" ]] && { printf '%s' "${candidate}"; return 0; }
  done
  return 1
}

# Build (or reuse) cosmos_configs/icons/steam-<appid>.icns from Steam artwork.
# Echoes the .icns path on success; returns non-zero (silently) when icons are
# disabled, no artwork exists, or the macOS converter is unavailable.
generate_icon() {
  local appid="$1"
  [[ "${COSMOS_SKIP_ICONS:-0}" == "1" ]] && return 1
  [[ -x "${ICON_TOOL}" ]] || return 1

  local src out
  src="$(find_icon_source "${appid}" "${STEAM_DIR}")" || return 1
  out="${ICONS_DIR}/steam-${appid}.icns"

  # Reuse a cached icon unless the source artwork is newer.
  if [[ -f "${out}" && "${out}" -nt "${src}" ]]; then
    printf '%s' "${out}"
    return 0
  fi

  mkdir -p "${ICONS_DIR}"
  if "${ICON_TOOL}" "${src}" "${out}" >/dev/null 2>&1; then
    printf '%s' "${out}"
    return 0
  fi
  return 1
}

# Drop generated icons whose game no longer has a generated config, so the icons
# cache mirrors the launcher set.
prune_orphan_icons() {
  [[ -d "${ICONS_DIR}" ]] || return 0
  local icns appid match found
  shopt -s nullglob
  for icns in "${ICONS_DIR}"/steam-*.icns; do
    appid="${icns##*/steam-}"; appid="${appid%.icns}"
    found=0
    for match in "${CONFIGS_DIR}/steam-${appid}.conf" "${CONFIGS_DIR}/steam-${appid}-"*.conf; do
      [[ -f "${match}" ]] && { found=1; break; }
    done
    (( found )) || rm -f "${icns}"
  done
  shopt -u nullglob
}

write_config() {
  local appid="$1" name="$2"
  local slug app_name bundle_id file
  slug="$(slugify "${name}")"
  app_name="$(safe_app_name "${name}") (Cosmos)"
  bundle_id="com.cosmos.steam-${appid}"
  file="${CONFIGS_DIR}/steam-${appid}${slug:+-${slug}}.conf"

  read_overrides "${appid}"

  local icns=""
  icns="$(generate_icon "${appid}")" || icns=""

  {
    printf '%s\n' "${AUTO_HEADER}"
    printf '# Steam: %s (App ID %s)\n' "${name}" "${appid}"
    if (( ${#OVERRIDE_NAMES[@]} > 0 )); then
      printf '# Merged extras from overrides/%s.env: %s\n' "${appid}" "${OVERRIDE_NAMES[*]}"
    else
      printf '# Tip: add persistent env/backend/args in cosmos_configs/overrides/%s.env\n' "${appid}"
    fi
    printf 'APP_NAME="%s"\n' "${app_name}"
    printf 'BUNDLE_ID="%s"\n' "${bundle_id}"
    # Icon from Steam artwork (build-time only). Skip it when the override file
    # supplies its own ICON_PATH so a user's custom icon wins outright.
    local b override_icon=0
    for b in ${OVERRIDE_BUILD_LINES[@]+"${OVERRIDE_BUILD_LINES[@]}"}; do
      [[ "${b}" == ICON_PATH=* ]] && override_icon=1
    done
    if [[ -n "${icns}" && "${override_icon}" -eq 0 ]]; then
      printf 'ICON_PATH="%s"\n' "${icns}"
    fi
    for b in ${OVERRIDE_BUILD_LINES[@]+"${OVERRIDE_BUILD_LINES[@]}"}; do
      printf '%s\n' "${b}"
    done
    printf '\n'
    printf 'RUN_ENV_NAMES=(\n'
    printf '  STEAM_GAME_ID\n'
    local n
    for n in ${OVERRIDE_NAMES[@]+"${OVERRIDE_NAMES[@]}"}; do
      printf '  %s\n' "${n}"
    done
    printf ')\n'
    printf '\n'
    printf 'STEAM_GAME_ID="%s"\n' "${appid}"
    local l
    for l in ${OVERRIDE_LINES[@]+"${OVERRIDE_LINES[@]}"}; do
      printf '%s\n' "${l}"
    done
  } > "${file}"
  printf '%s' "${file}"
}

main() {
  parse_arguments "$@"

  local steam_dir
  steam_dir="$(find_steam_dir)"
  [[ -n "${steam_dir}" ]] || die "Steam not found in the Wine prefix (${WINEPREFIX}). Launch Steam via Cosmos first."
  STEAM_DIR="${steam_dir}"

  collect_curated_appids

  # Gather (appid, name) pairs from every library, deduped by appid.
  local -a appids=() names=()
  local seen=""
  local steamapps acf appid name
  while IFS= read -r steamapps; do
    [[ -d "${steamapps}" ]] || continue
    shopt -s nullglob
    for acf in "${steamapps}"/appmanifest_*.acf; do
      appid="${acf##*/appmanifest_}"; appid="${appid%.acf}"
      [[ "${appid}" =~ ^[0-9]+$ ]] || continue
      [[ "${seen}" == *" ${appid} "* ]] && continue
      seen+=" ${appid} "
      name="$(awk -F'"' '$2=="name"{print $4; exit}' "${acf}")"
      [[ -n "${name}" ]] || name="Steam App ${appid}"
      is_ignored_app "${appid}" "${name}" && continue
      appids+=("${appid}"); names+=("${name}")
    done
    shopt -u nullglob
  done < <(collect_steamapps_dirs "${steam_dir}")

  if (( ${#appids[@]} == 0 )); then
    if [[ "${MODE}" == "list" ]]; then
      die "No installed Steam games found under ${steam_dir}."
    fi
    # Still prune previously generated configs so launchers for games that have
    # since been uninstalled do not linger.
    log "No installed Steam games found under ${steam_dir}."
    mkdir -p "${CONFIGS_DIR}"
    remove_stale_generated
    prune_orphan_icons
    echo "Removed any previously generated launcher configs."
    return
  fi

  log "Detected ${#appids[@]} installed Steam game(s) in ${WINEPREFIX}"

  if [[ "${MODE}" == "list" ]]; then
    local i
    for i in "${!appids[@]}"; do
      local note=""
      is_curated "${appids[$i]}" && note="  [curated config exists]"
      printf '  %-8s %s%s\n' "${appids[$i]}" "${names[$i]}" "${note}"
    done
    return
  fi

  mkdir -p "${CONFIGS_DIR}"
  remove_stale_generated

  local written=0 skipped=0 i file
  for i in "${!appids[@]}"; do
    if is_curated "${appids[$i]}"; then
      printf '  skip   %-8s %s (curated config already exists)\n' "${appids[$i]}" "${names[$i]}"
      skipped=$((skipped + 1))
      continue
    fi
    file="$(write_config "${appids[$i]}" "${names[$i]}")"
    local icon_note=""
    grep -q '^ICON_PATH=' "${file}" && icon_note="  [icon]"
    printf '  write  %-8s %s -> %s%s\n' "${appids[$i]}" "${names[$i]}" "${file##*/}" "${icon_note}"
    written=$((written + 1))
  done

  prune_orphan_icons

  log "Wrote ${written} generated config(s); skipped ${skipped} curated."

  if [[ "${MODE}" == "install" ]]; then
    log "Building launchers via install_cosmos.command"
    "${SCRIPT_DIR}/install_cosmos.command"
  else
    echo "Next: run ./install_cosmos.command to build the .app launchers into '/Applications/Cosmos Apps'."
  fi
}

main "$@"
