#!/usr/bin/env bash
set -euo pipefail

# Cosmos roadmap milestone 0.2 — auto-detect installed Steam games and turn them
# into launcher configs that install_cosmos.command builds into .app bundles.
#
# It scans the Steam libraries inside the Wine prefix (libraryfolders.vdf +
# appmanifest_*.acf), then writes one generated config per installed game into
# cosmos_configs/ named "steam-<appid>-<slug>.conf". Games that already have a
# hand-curated config (matched by Steam App ID) are skipped so curated presets win.
#
# Per-game extras (graphics backend, extra env vars, launch args) can be attached
# to an auto-detected game by dropping a "cosmos_configs/overrides/<appid>.env"
# file with simple KEY=VALUE lines. Those are merged into the generated config and
# survive refreshes. See cosmos_configs/overrides/README.md.
#
# Each game's icon is built from Steam's locally-cached artwork (appcache/
# librarycache) into cosmos_configs/icons/steam-<appid>.icns and referenced from
# the generated config via ICON_PATH. This needs macOS (sips + iconutil); when the
# tools or the artwork are missing the launcher keeps the default Cosmos icon.
#
# Usage:
#   detect_steam_games.command            # default: refresh generated configs
#   detect_steam_games.command --list     # print detected games, write nothing
#   detect_steam_games.command --write     # write/refresh generated configs (default)
#   detect_steam_games.command --install   # write configs, then build all launchers
#   detect_steam_games.command --verify    # list games + verify installdir on disk

SCRIPT_DIR="${SCRIPT_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)}"
# shellcheck source=scripts/lib/steam_lib.sh
source "${SCRIPT_DIR}/scripts/lib/steam_lib.sh"
# shellcheck source=scripts/lib/profile_lib.sh
source "${SCRIPT_DIR}/scripts/lib/profile_lib.sh"
PROFILES_DIR="${SCRIPT_DIR}/profiles"
# Writable user-data root, matching run.command. Generated configs/icons live
# under here when Cosmos runs from an installed app bundle.
COSMOS_SUPPORT_DIR="${COSMOS_SUPPORT_DIR:-$HOME/Library/Application Support/Cosmos}"

# Choose where generated configs/icons/overrides live:
#   1. an explicit COSMOS_CONFIGS_DIR wins;
#   2. from an installed .app bundle (read-only Resources), use Application
#      Support and seed it once with the curated configs shipped in the bundle;
#   3. otherwise (a dev checkout) use the cosmos_configs/ next to this script.
resolve_configs_dir() {
  if [[ -n "${COSMOS_CONFIGS_DIR:-}" ]]; then
    printf '%s' "${COSMOS_CONFIGS_DIR}"
    return
  fi
  local bundled="${SCRIPT_DIR}/cosmos_configs"
  if [[ "${SCRIPT_DIR}" == *.app/Contents/Resources ]]; then
    local data="${COSMOS_SUPPORT_DIR}/cosmos_configs"
    mkdir -p "${data}"
    if [[ -d "${bundled}" ]]; then
      # Copy curated configs without clobbering the user's existing edits.
      cp -Rn "${bundled}/." "${data}/" 2>/dev/null || true
    fi
    printf '%s' "${data}"
    return
  fi
  printf '%s' "${bundled}"
}

CONFIGS_DIR="$(resolve_configs_dir)"
# User-authored per-game overrides keyed by Steam App ID (overrides/<appid>.env).
# These are merged into the generated config so extra env / backend / launch args
# survive a refresh (which otherwise overwrites the auto-generated configs).
OVERRIDES_DIR="${COSMOS_OVERRIDES_DIR:-${CONFIGS_DIR}/overrides}"
WINEPREFIX="${WINEPREFIX:-$HOME/.wine-steam-11}"

# Per-game .icns icons are converted from Steam's locally-cached artwork into this
# directory and referenced from the generated configs via ICON_PATH. Set
# COSMOS_SKIP_ICONS=1 to skip icon generation (e.g. on a fresh prefix where Steam
# has not downloaded library art yet). COSMOS_ICON_TOOL overrides the converter.
ICONS_DIR="${COSMOS_ICONS_DIR:-${CONFIGS_DIR}/icons}"
# Locate the icon converter in both the repo layout (scripts/) and the flattened
# layout used inside an installed app bundle's Resources.
if [[ -n "${COSMOS_ICON_TOOL:-}" ]]; then
  ICON_TOOL="${COSMOS_ICON_TOOL}"
elif [[ -x "${SCRIPT_DIR}/scripts/make_app_icon.command" ]]; then
  ICON_TOOL="${SCRIPT_DIR}/scripts/make_app_icon.command"
else
  ICON_TOOL="${SCRIPT_DIR}/make_app_icon.command"
fi
STEAM_DIR=""

AUTO_HEADER="# AUTO-GENERATED by detect_steam_games.command. Re-run to refresh; edits will be overwritten."
MODE="write"
JSON_OUTPUT=0
SNAPSHOT_FILE="${COSMOS_STEAM_SNAPSHOT:-${COSMOS_SUPPORT_DIR}/steam-library.snapshot}"

# Steam App IDs that are tools/runtimes/redistributables rather than games.
# See docs/OPEN_SOURCE_INTEGRATIONS.md for detection hardening notes.
IGNORED_APPIDS=" 218 228980 931380 1054830 1070560 1391110 1493710 1628350 "

log() { printf "\n==> %s\n" "$1" >&2; }
die() { printf "Error: %s\n" "$1" >&2; exit 1; }

steam_refresh_library() {
  [[ -x "${SCRIPT_DIR}/library.command" ]] || return 0
  WINEPREFIX="${WINEPREFIX}" "${SCRIPT_DIR}/library.command" scan >/dev/null 2>&1 || true
}

usage() {
  cat <<'EOF'
Auto-detect installed Steam games and turn them into Cosmos launcher configs.

Usage: detect_steam_games.command [--list|--write|--install|--verify|--sync] [--json]
  --list      Print detected installed Steam games and exit (writes nothing).
  --write     (default) Write/refresh generated configs in cosmos_configs/.
  --install   Write configs, then run install_cosmos.command to build launchers.
  --sync      Build launchers for newly installed games since the last snapshot.
  --verify    Run scripts/verify_steam_detection.command after listing.
  --json      With --list, print machine-readable JSON to stdout.

Environment (sync):
  COSMOS_STEAM_SNAPSHOT     Override snapshot path (per-bottle sync from the app).
  COSMOS_SYNC_SEED_ONLY=1   With --sync and no snapshot yet, record App IDs only.
  COSMOS_SYNC_FULL=1        Required for first --sync without snapshot (builds launchers).

Partial installs (downloads in progress) are skipped by default. Set
COSMOS_DETECT_INCLUDE_PARTIAL=1 to include them.

Set COSMOS_STEAM_NATIVE_SCAN=1 to also scan native macOS/Linux Steam libraries
(validation / discovery). Native-only titles are listed but not turned into
Wine launchers unless they also appear in the Wine prefix.
EOF
}

parse_arguments() {
  while (($#)); do
    case "$1" in
      ""|--write) MODE="write" ;;
      --list) MODE="list" ;;
      --install) MODE="install" ;;
      --sync) MODE="sync" ;;
      --verify) MODE="verify" ;;
      --json) JSON_OUTPUT=1 ;;
      --help|-h) usage; exit 0 ;;
      *) die "Unknown argument: $1" ;;
    esac
    shift
  done
}

snapshot_load_ids() {
  [[ -f "${SNAPSHOT_FILE}" ]] || return 0
  tr -d '\r' < "${SNAPSHOT_FILE}" | sed '/^[[:space:]]*$/d'
}

snapshot_save_ids() {
  mkdir -p "${COSMOS_SUPPORT_DIR}"
  : > "${SNAPSHOT_FILE}"
  local id
  for id in "$@"; do
    printf '%s\n' "${id}" >> "${SNAPSHOT_FILE}"
  done
}

appid_in_snapshot() {
  local id="$1" line
  [[ -f "${SNAPSHOT_FILE}" ]] || return 1
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%%$'\r'}"
    [[ "${line}" == "${id}" ]] && return 0
  done < "${SNAPSHOT_FILE}"
  return 1
}

emit_json_game_list() {
  local i
  printf '['
  for i in "${!appids[@]}"; do
    (( i > 0 )) && printf ','
    python3 - "${appids[$i]}" "${names[$i]}" <<'PY'
import json, sys
print(json.dumps({"appid": sys.argv[1], "name": sys.argv[2]}), end="")
PY
  done
  printf ']\n'
}

# True for Steam entries that are tools/runtimes rather than games, so they don't
# become junk launchers (e.g. Steamworks Common Redistributables, Proton, runtimes).
is_ignored_app() {
  local appid="$1" name="$2"
  [[ "${IGNORED_APPIDS}" == *" ${appid} "* ]] && return 0
  printf '%s' "${name}" | grep -Eqi \
    'steamworks common redistributables|steam linux runtime|^proton( |$|-)|^steamvr$' && return 0
  return 1
}

slugify() {
  printf '%s' "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

# Sanitize a Steam name into something safe for an APP_NAME / .app directory:
# '/' and ':' are not valid in macOS file names, and characters that are special
# inside a double-quoted shell string are escaped because the generated config is
# sourced by install_cosmos.command.
safe_app_name() {
  local name="$1"
  name="${name//\\/}"          # drop backslashes
  name="${name//\//-}"         # '/' not allowed in file names
  name="${name//:/ -}"         # ':' shows as '/' in Finder
  name="${name//\"/}"          # drop double quotes (would close the string)
  name="${name//\$/}"          # drop '$' (no expansion when sourced)
  name="${name//\`/}"          # drop backticks (no command substitution)
  printf '%s' "${name}"
}

# Thin wrappers — shared logic lives in scripts/lib/steam_lib.sh.
win_to_unix() { steam_win_to_unix "$@"; }
find_steam_dir() { steam_find_steam_dir; }
collect_steamapps_dirs() { steam_collect_steamapps_dirs "$@"; }
collect_detection_steamapps_dirs() { steam_collect_detection_steamapps_dirs "$@"; }
collect_native_steamapps_dirs() { steam_collect_native_steamapps_dirs; }

# Space-padded App ID lists for dual-path source tracking (bash 3.2 safe).
DETECT_WINE_APPIDS=""
DETECT_NATIVE_APPIDS=""

detect_mark_wine_appid() {
  local id="$1"
  [[ "${DETECT_WINE_APPIDS}" == *" ${id} "* ]] || DETECT_WINE_APPIDS+=" ${id} "
}

detect_mark_native_appid() {
  local id="$1"
  [[ "${DETECT_NATIVE_APPIDS}" == *" ${id} "* ]] || DETECT_NATIVE_APPIDS+=" ${id} "
}

detect_appid_source_label() {
  local id="$1"
  local in_wine=0 in_native=0
  [[ "${DETECT_WINE_APPIDS}" == *" ${id} "* ]] && in_wine=1
  [[ "${DETECT_NATIVE_APPIDS}" == *" ${id} "* ]] && in_native=1
  if (( in_wine && in_native )); then
    printf '  [wine+native]'
  elif (( in_native )); then
    printf '  [native only]'
  elif (( in_wine )); then
    printf ''
  else
    printf ''
  fi
}

detect_appid_in_wine_prefix() {
  [[ "${DETECT_WINE_APPIDS}" == *" $1 "* ]]
}

scan_steamapps_library() {
  local steamapps="$1" source="$2"
  local acf appid name
  [[ -d "${steamapps}" ]] || return 0
  shopt -s nullglob
  for acf in "${steamapps}"/appmanifest_*.acf; do
    appid="${acf##*/appmanifest_}"; appid="${appid%.acf}"
    [[ "${appid}" =~ ^[0-9]+$ ]] || continue
    name="$(steam_acf_read_field "${acf}" "name")"
    [[ -n "${name}" ]] || name="Steam App ${appid}"
    is_ignored_app "${appid}" "${name}" && continue
    if ! steam_acf_is_playable "${acf}"; then
      DETECT_SKIPPED_PARTIAL=$((DETECT_SKIPPED_PARTIAL + 1))
      continue
    fi
    case "${source}" in
      wine) detect_mark_wine_appid "${appid}" ;;
      native) detect_mark_native_appid "${appid}" ;;
    esac
    [[ "${DETECT_SEEN}" == *" ${appid} "* ]] && continue
    DETECT_SEEN+=" ${appid} "
    DETECT_APPIDS+=("${appid}")
    DETECT_NAMES+=("${name}")
  done
  shopt -u nullglob
}

# Record Steam App IDs that already have a hand-curated (non auto-generated) config.
curated_appids=""
collect_curated_appids() {
  local cfg aid
  shopt -s nullglob
  for cfg in "${CONFIGS_DIR}"/*.conf; do
    grep -q 'AUTO-GENERATED by detect_steam_games' "${cfg}" && continue
    aid="$(sed -n 's/^STEAM_GAME_ID="\{0,1\}\([0-9][0-9]*\)"\{0,1\}.*/\1/p' "${cfg}" | head -n1)"
    [[ -n "${aid}" ]] && curated_appids+=" ${aid} "
  done
  shopt -u nullglob
}

is_curated() { [[ "${curated_appids}" == *" $1 "* ]]; }

# When a v0 YAML profile exists and the user has not authored an override yet,
# export recommended backend / env into overrides/<appid>.env so auto-generated
# launchers pick up known-good defaults (roadmap 0.4).
merge_profile_override() {
  local appid="$1"
  local override_file="${OVERRIDES_DIR}/${appid}.env"
  [[ -f "${override_file}" ]] && return 1
  local profile_file
  profile_file="$(profile_find_by_appid "${PROFILES_DIR}" "${appid}")" || return 1
  profile_export_override_to "${profile_file}" "${appid}" "${override_file}" || return 1
  printf '%s' "${profile_file}"
}

remove_stale_generated() {
  local cfg
  shopt -s nullglob
  for cfg in "${CONFIGS_DIR}"/steam-*.conf; do
    grep -q 'AUTO-GENERATED by detect_steam_games' "${cfg}" && rm -f "${cfg}"
  done
  shopt -u nullglob
}

# During --sync, drop auto-generated configs for games no longer installed.
# Curated configs and hand-edited files are left untouched.
prune_uninstalled_generated() {
  local -a current=("$@")
  local cfg appid found id removed=0
  shopt -s nullglob
  for cfg in "${CONFIGS_DIR}"/steam-*.conf; do
    grep -q 'AUTO-GENERATED by detect_steam_games' "${cfg}" || continue
    appid="$(grep -E '^STEAM_GAME_ID=' "${cfg}" | head -1 | cut -d= -f2- | tr -d '"')"
    [[ -n "${appid}" ]] || continue
    found=0
    for id in "${current[@]}"; do
      [[ "${id}" == "${appid}" ]] && { found=1; break; }
    done
    if (( ! found )); then
      rm -f "${cfg}"
      removed=$((removed + 1))
    fi
  done
  shopt -u nullglob
  printf '%s' "${removed}"
}

# Keys that install_cosmos.command consumes at build time only (they are not
# runtime env, so they must NOT go into RUN_ENV_NAMES). APP_NAME / BUNDLE_ID /
# STEAM_GAME_ID are managed by this script and ignored if an override sets them.
OVERRIDE_RESERVED_KEYS=" STEAM_GAME_ID APP_NAME BUNDLE_ID "
OVERRIDE_BUILD_KEYS=" ICON_PATH APP_VERSION LS_MINIMUM_SYSTEM_VERSION "

# Populate the OVERRIDE_* globals from cosmos_configs/overrides/<appid>.env:
#   OVERRIDE_NAMES        runtime env var names (added to RUN_ENV_NAMES)
#   OVERRIDE_LINES        runtime assignment lines
#   OVERRIDE_BUILD_LINES  build-time assignment lines (e.g. a custom ICON_PATH)
# Only well-formed KEY=VALUE lines with an upper-snake-case KEY are accepted;
# everything else (comments, blanks, stray shell) is ignored so the override file
# cannot smuggle arbitrary commands into the sourced config.
# (Globals + manual parallel arrays keep this compatible with macOS bash 3.2,
# which has no namerefs.)
OVERRIDE_NAMES=()
OVERRIDE_LINES=()
OVERRIDE_BUILD_LINES=()
read_overrides() {
  local appid="$1"
  OVERRIDE_NAMES=()
  OVERRIDE_LINES=()
  OVERRIDE_BUILD_LINES=()
  local override_file="${OVERRIDES_DIR}/${appid}.env"
  [[ -f "${override_file}" ]] || return 0

  local line key existing seen
  while IFS= read -r line || [[ -n "${line}" ]]; do
    line="${line%$'\r'}"                       # tolerate CRLF
    [[ "${line}" =~ ^[[:space:]]*(#|$) ]] && continue
    [[ "${line}" == *=* ]] || continue
    key="${line%%=*}"
    key="${key//[[:space:]]/}"
    [[ "${key}" =~ ^[A-Z][A-Z0-9_]*$ ]] || continue
    [[ "${OVERRIDE_RESERVED_KEYS}" == *" ${key} "* ]] && continue
    if [[ "${OVERRIDE_BUILD_KEYS}" == *" ${key} "* ]]; then
      OVERRIDE_BUILD_LINES+=("${key}=${line#*=}")
      continue
    fi
    # Skip a runtime key already collected so RUN_ENV_NAMES and the assignments
    # stay 1:1.
    seen=0
    for existing in ${OVERRIDE_NAMES[@]+"${OVERRIDE_NAMES[@]}"}; do
      [[ "${existing}" == "${key}" ]] && { seen=1; break; }
    done
    (( seen )) && continue
    OVERRIDE_NAMES+=("${key}")
    OVERRIDE_LINES+=("${key}=${line#*=}")
  done < "${override_file}"
}

# Echo the best locally-cached Steam artwork file for an App ID, or nothing.
# Preference order favors a square clienticon, then portrait/landscape capsules
# (which get centre-cropped to square by the converter). Both the historical flat
# naming and the newer per-appid subfolder layout are probed.
find_icon_source() {
  local appid="$1" steam_dir="$2"
  local lc="${steam_dir}/appcache/librarycache"
  local candidate
  for candidate in \
    "${lc}/${appid}_icon.jpg" \
    "${lc}/${appid}/icon.jpg" \
    "${lc}/${appid}_library_600x900.jpg" \
    "${lc}/${appid}/library_600x900.jpg" \
    "${lc}/${appid}_header.jpg" \
    "${lc}/${appid}/header.jpg" \
    "${lc}/${appid}_logo.png" \
    "${lc}/${appid}/logo.png"; do
    [[ -f "${candidate}" ]] && { printf '%s' "${candidate}"; return 0; }
  done
  return 1
}

# Build (or reuse) cosmos_configs/icons/steam-<appid>.icns from Steam artwork.
# Echoes the .icns path on success; returns non-zero (silently) when icons are
# disabled, no artwork exists, or the macOS converter is unavailable.
generate_icon() {
  local appid="$1"
  [[ "${COSMOS_SKIP_ICONS:-0}" == "1" ]] && return 1
  [[ -x "${ICON_TOOL}" ]] || return 1

  local src out
  src="$(find_icon_source "${appid}" "${STEAM_DIR}")" || return 1
  out="${ICONS_DIR}/steam-${appid}.icns"

  # Reuse a cached icon unless the source artwork is newer.
  if [[ -f "${out}" && "${out}" -nt "${src}" ]]; then
    printf '%s' "${out}"
    return 0
  fi

  mkdir -p "${ICONS_DIR}"
  if "${ICON_TOOL}" "${src}" "${out}" >/dev/null 2>&1; then
    printf '%s' "${out}"
    return 0
  fi
  return 1
}

# Drop generated icons whose game no longer has a generated config, so the icons
# cache mirrors the launcher set.
prune_orphan_icons() {
  [[ -d "${ICONS_DIR}" ]] || return 0
  local icns appid match found
  shopt -s nullglob
  for icns in "${ICONS_DIR}"/steam-*.icns; do
    appid="${icns##*/steam-}"; appid="${appid%.icns}"
    found=0
    for match in "${CONFIGS_DIR}/steam-${appid}.conf" "${CONFIGS_DIR}/steam-${appid}-"*.conf; do
      [[ -f "${match}" ]] && { found=1; break; }
    done
    (( found )) || rm -f "${icns}"
  done
  shopt -u nullglob
}

write_config() {
  local appid="$1" name="$2"
  local slug app_name bundle_id file
  slug="$(slugify "${name}")"
  app_name="$(safe_app_name "${name}") (Cosmos)"
  bundle_id="com.cosmos.steam-${appid}"
  file="${CONFIGS_DIR}/steam-${appid}${slug:+-${slug}}.conf"

  read_overrides "${appid}"

  local icns=""
  icns="$(generate_icon "${appid}")" || icns=""

  {
    printf '%s\n' "${AUTO_HEADER}"
    printf '# Steam: %s (App ID %s)\n' "${name}" "${appid}"
    if (( ${#OVERRIDE_NAMES[@]} > 0 )); then
      printf '# Merged extras from overrides/%s.env: %s\n' "${appid}" "${OVERRIDE_NAMES[*]}"
    else
      printf '# Tip: add persistent env/backend/args in cosmos_configs/overrides/%s.env\n' "${appid}"
    fi
    printf 'APP_NAME="%s"\n' "${app_name}"
    printf 'BUNDLE_ID="%s"\n' "${bundle_id}"
    # Icon from Steam artwork (build-time only). Skip it when the override file
    # supplies its own ICON_PATH so a user's custom icon wins outright.
    local b override_icon=0
    for b in ${OVERRIDE_BUILD_LINES[@]+"${OVERRIDE_BUILD_LINES[@]}"}; do
      [[ "${b}" == ICON_PATH=* ]] && override_icon=1
    done
    if [[ -n "${icns}" && "${override_icon}" -eq 0 ]]; then
      printf 'ICON_PATH="%s"\n' "${icns}"
    fi
    for b in ${OVERRIDE_BUILD_LINES[@]+"${OVERRIDE_BUILD_LINES[@]}"}; do
      printf '%s\n' "${b}"
    done
    printf '\n'
    printf 'RUN_ENV_NAMES=(\n'
    printf '  STEAM_GAME_ID\n'
    local n
    for n in ${OVERRIDE_NAMES[@]+"${OVERRIDE_NAMES[@]}"}; do
      printf '  %s\n' "${n}"
    done
    printf ')\n'
    printf '\n'
    printf 'STEAM_GAME_ID="%s"\n' "${appid}"
    local l
    for l in ${OVERRIDE_LINES[@]+"${OVERRIDE_LINES[@]}"}; do
      printf '%s\n' "${l}"
    done
  } > "${file}"
  printf '%s' "${file}"
}

main() {
  parse_arguments "$@"

  local steam_dir
  steam_dir="$(find_steam_dir)"
  [[ -n "${steam_dir}" ]] || die "Steam not found in the Wine prefix (${WINEPREFIX}). Launch Steam via Cosmos first."
  STEAM_DIR="${steam_dir}"

  collect_curated_appids

  # Gather (appid, name) pairs from Wine prefix libraries (and optional native Steam).
  local -a appids=() names=()
  DETECT_WINE_APPIDS=""
  DETECT_NATIVE_APPIDS=""
  DETECT_SEEN=""
  DETECT_SKIPPED_PARTIAL=0
  DETECT_APPIDS=()
  DETECT_NAMES=()
  local steamapps

  while IFS= read -r steamapps; do
    scan_steamapps_library "${steamapps}" "wine"
  done < <(collect_steamapps_dirs "${steam_dir}")

  if [[ "${COSMOS_STEAM_NATIVE_SCAN:-0}" == "1" ]]; then
    while IFS= read -r steamapps; do
      scan_steamapps_library "${steamapps}" "native"
    done < <(collect_native_steamapps_dirs)
  fi

  appids=("${DETECT_APPIDS[@]}")
  names=("${DETECT_NAMES[@]}")

  if (( DETECT_SKIPPED_PARTIAL > 0 )); then
    printf '  (skipped %s partial/in-progress install(s); set COSMOS_DETECT_INCLUDE_PARTIAL=1 to include)\n' "${DETECT_SKIPPED_PARTIAL}" >&2
  fi

  if (( ${#appids[@]} == 0 )); then
    if [[ "${MODE}" == "list" ]]; then
      die "No installed Steam games found under ${steam_dir}."
    fi
    # Still prune previously generated configs so launchers for games that have
    # since been uninstalled do not linger.
    log "No installed Steam games found under ${steam_dir}."
    mkdir -p "${CONFIGS_DIR}"
    local removed=0
    if [[ "${MODE}" == "sync" ]]; then
      removed="$(prune_uninstalled_generated)"
      snapshot_save_ids
    else
      remove_stale_generated
    fi
    prune_orphan_icons
    steam_refresh_library
    if [[ "${MODE}" == "sync" ]]; then
      printf 'sync_status=updated\n'
      printf 'sync_new=0\n'
      printf 'sync_removed=%s\n' "${removed}"
      echo "Pruned ${removed} uninstalled game config(s)."
      return
    fi
    echo "Removed any previously generated launcher configs."
    return
  fi

  if [[ "${COSMOS_STEAM_NATIVE_SCAN:-0}" == "1" ]]; then
    log "Detected ${#appids[@]} installed Steam game(s) (Wine prefix + native Steam scan)"
  else
    log "Detected ${#appids[@]} installed Steam game(s) in ${WINEPREFIX}"
  fi

  if [[ "${MODE}" == "list" || "${MODE}" == "verify" ]]; then
    if [[ "${MODE}" == "list" && "${JSON_OUTPUT}" == "1" ]]; then
      emit_json_game_list
      return
    fi
    local i
    for i in "${!appids[@]}"; do
      local note=""
      note="$(detect_appid_source_label "${appids[$i]}")"
      is_curated "${appids[$i]}" && note+="  [curated config exists]"
      if profile_find_by_appid "${PROFILES_DIR}" "${appids[$i]}" >/dev/null 2>&1; then
        local pf status backend
        pf="$(profile_find_by_appid "${PROFILES_DIR}" "${appids[$i]}")"
        status="$(profile_get_scalar "${pf}" status)"
        backend="$(profile_get_scalar "${pf}" recommended_backend)"
        note+="  [profile: ${status:-?}/${backend:-?}]"
      fi
      printf '  %-8s %s%s\n' "${appids[$i]}" "${names[$i]}" "${note}"
    done
    if [[ "${MODE}" == "verify" ]]; then
      local verifier="${SCRIPT_DIR}/scripts/verify_steam_detection.command"
      [[ -x "${verifier}" ]] || verifier="${SCRIPT_DIR}/verify_steam_detection.command"
      if [[ -x "${verifier}" ]]; then
        log "Running detection verification"
        WINEPREFIX="${WINEPREFIX}" "${verifier}" || true
      else
        echo "Verifier not found (expected scripts/verify_steam_detection.command)."
      fi
    fi
    return
  fi

  if [[ "${MODE}" == "sync" && ! -f "${SNAPSHOT_FILE}" ]]; then
    if [[ "${COSMOS_SYNC_SEED_ONLY:-0}" == "1" ]]; then
      snapshot_save_ids "${appids[@]}"
      printf 'sync_status=seeded\n'
      printf 'sync_new=0\n'
      printf 'sync_removed=0\n'
      echo "Initialized Steam library snapshot (${#appids[@]} game(s))."
      return
    fi
    if [[ "${COSMOS_SYNC_FULL:-0}" != "1" ]]; then
      die "No steam-library snapshot at ${SNAPSHOT_FILE}. Run --install once, or set COSMOS_SYNC_FULL=1 (build) or COSMOS_SYNC_SEED_ONLY=1 (track only)."
    fi
  fi

  mkdir -p "${CONFIGS_DIR}"
  if [[ "${MODE}" != "sync" ]]; then
    remove_stale_generated
  fi

  local written=0 skipped=0 i file
  local -a new_configs=()
  for i in "${!appids[@]}"; do
    if ! detect_appid_in_wine_prefix "${appids[$i]}"; then
      printf '  skip   %-8s %s (native Steam only — not in Wine prefix)\n' \
        "${appids[$i]}" "${names[$i]}"
      skipped=$((skipped + 1))
      continue
    fi
    if [[ "${MODE}" == "sync" ]] && appid_in_snapshot "${appids[$i]}"; then
      skipped=$((skipped + 1))
      continue
    fi
    if is_curated "${appids[$i]}"; then
      printf '  skip   %-8s %s (curated config already exists)\n' "${appids[$i]}" "${names[$i]}"
      skipped=$((skipped + 1))
      continue
    fi
    local profile_note=""
    if merge_profile_override "${appids[$i]}"; then
      profile_note="  [profile override]"
    fi
    file="$(write_config "${appids[$i]}" "${names[$i]}")"
    new_configs+=("${file}")
    local icon_note=""
    grep -q '^ICON_PATH=' "${file}" && icon_note="  [icon]"
    printf '  write  %-8s %s -> %s%s%s\n' "${appids[$i]}" "${names[$i]}" "${file##*/}" "${profile_note}" "${icon_note}"
    written=$((written + 1))
  done

  if [[ "${MODE}" == "sync" ]]; then
    local removed
    removed="$(prune_uninstalled_generated "${appids[@]}")"
    prune_orphan_icons
    if (( written == 0 )); then
      snapshot_save_ids "${appids[@]}"
      if (( removed > 0 )); then
        printf 'sync_status=updated\n'
        printf 'sync_new=0\n'
        printf 'sync_removed=%s\n' "${removed}"
        echo "Pruned ${removed} uninstalled game config(s) (${#appids[@]} remaining)."
        return
      fi
      printf 'sync_status=current\n'
      printf 'sync_new=0\n'
      printf 'sync_removed=0\n'
      echo "Steam library is up to date (${#appids[@]} game(s))."
      return
    fi
    log "Syncing ${written} new game(s)"
    if [[ "${COSMOS_SYNC_DRY_RUN:-0}" != "1" ]]; then
      log "Building launchers via install_cosmos.command"
      COSMOS_ALLOW_USER_APPS="${COSMOS_ALLOW_USER_APPS:-1}" \
        "${SCRIPT_DIR}/install_cosmos.command" "${new_configs[@]}"
    fi
    snapshot_save_ids "${appids[@]}"
    printf 'sync_status=updated\n'
    printf 'sync_new=%s\n' "${written}"
    printf 'sync_removed=%s\n' "${removed}"
    return
  fi

  prune_orphan_icons

  log "Wrote ${written} generated config(s); skipped ${skipped} curated."
  steam_refresh_library
  snapshot_save_ids "${appids[@]}"

  if [[ "${MODE}" == "install" ]]; then
    log "Building launchers via install_cosmos.command"
    COSMOS_ALLOW_USER_APPS="${COSMOS_ALLOW_USER_APPS:-1}" \
      "${SCRIPT_DIR}/install_cosmos.command"
  else
    echo "Next: run ./install_cosmos.command to build the .app launchers into '/Applications/Cosmos Apps'."
  fi
}

main "$@"
