#!/usr/bin/env bash
set -euo pipefail

# Cosmos profile loader (roadmap 0.4) — read YAML profiles and apply settings.
# See docs/PROFILE_FORMAT.md and docs/LUTRIS_MAPPING.md.

SCRIPT_DIR="${SCRIPT_DIR:-$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)}"
PROFILE_LIB="${SCRIPT_DIR}/scripts/lib/profile_lib.sh"
PROFILES_DIR="${SCRIPT_DIR}/profiles"
COSMOS_SUPPORT_DIR="${COSMOS_SUPPORT_DIR:-$HOME/Library/Application Support/Cosmos}"
OVERRIDES_DIR="${COSMOS_OVERRIDES_DIR:-${COSMOS_SUPPORT_DIR}/cosmos_configs/overrides}"

# shellcheck source=scripts/lib/profile_lib.sh
source "${PROFILE_LIB}"

log() { printf "\n==> %s\n" "$1"; }
die() { printf "Error: %s\n" "$1" >&2; exit 1; }

usage() {
  cat <<'EOF'
Cosmos profile manager — v0 YAML profiles under profiles/.

Usage: profile.command <command> [args]

Commands:
  list                          List profiles (store / appid / name).
  show <path-or-id>             Print resolved settings from a profile file.
  export-override <path> <appid> Write cosmos_configs/overrides/<appid>.env from profile.
  apply <path>                  export-override + install-deps + apply-fixes from profile.
  for-appid <appid> <cmd...>    Run show|apply using the profile matching steam_appid.

Examples:
  profile.command list
  profile.command show profiles/steam/steam-250900-binding-of-isaac.yaml
  profile.command export-override profiles/steam/steam-250900-binding-of-isaac.yaml 250900
  profile.command apply profiles/steam/steam-22380-fallout-new-vegas.yaml
EOF
}

resolve_profile() {
  local arg="${1:-}"
  [[ -n "${arg}" ]] || return 1
  if [[ -f "${arg}" ]]; then
    printf '%s' "${arg}"
    return 0
  fi
  local f
  shopt -s nullglob
  for f in "${PROFILES_DIR}"/*/"${arg}".yaml "${PROFILES_DIR}"/*/"${arg}".yml \
           "${PROFILES_DIR}"/*/*"${arg}"*.yaml; do
    [[ -f "${f}" ]] && { printf '%s' "${f}"; shopt -u nullglob; return 0; }
  done
  shopt -u nullglob
  return 1
}

cmd_list() {
  local f store appid name
  shopt -s nullglob
  for f in "${PROFILES_DIR}"/*/*.yaml "${PROFILES_DIR}"/*/*.yml; do
    [[ -f "${f}" ]] || continue
    store="$(profile_get_scalar "${f}" store)"
    appid="$(profile_get_scalar "${f}" steam_appid)"
    name="$(profile_get_scalar "${f}" name)"
    printf '  %-8s %-10s %s\n' "${appid:-"—"}" "${store:-"?"}" "${name:-"${f}"}"
  done
  shopt -u nullglob
}

cmd_show() {
  local file; file="$(resolve_profile "${1:-}")" || die "Profile not found: $1"
  log "Profile: ${file}"
  printf '  id:                  %s\n' "$(profile_get_scalar "${file}" id)"
  printf '  name:                %s\n' "$(profile_get_scalar "${file}" name)"
  printf '  store:               %s\n' "$(profile_get_scalar "${file}" store)"
  printf '  steam_appid:         %s\n' "$(profile_get_scalar "${file}" steam_appid)"
  printf '  status:              %s\n' "$(profile_get_scalar "${file}" status)"
  printf '  recommended_backend: %s\n' "$(profile_get_scalar "${file}" recommended_backend)"
  printf '  windows_version:     %s\n' "$(profile_get_scalar "${file}" settings.windows_version)"
  printf '  retina:              %s\n' "$(profile_get_scalar "${file}" settings.retina)"
  echo "  settings.env:"
  local env_keys="DXMT_CONFIG STEAM_GAME_ARGS COSMOS_BACKEND"
  local k v
  for k in ${env_keys}; do
    v="$(profile_get_env_line "${file}" "${k}")"
    [[ -n "${v}" ]] && printf '    %s=%s\n' "${k}" "${v}"
  done
  echo "  dependencies:"
  profile_list_dependencies "${file}" | sed 's/^/    /' || echo "    (none)"
  echo "  fixes:"
  profile_list_fixes "${file}" | sed 's/^/    /' || echo "    (none)"
}

cmd_export_override() {
  local file appid
  file="$(resolve_profile "${1:-}")" || die "Profile not found: $1"
  appid="${2:-$(profile_get_scalar "${file}" steam_appid)}"
  [[ "${appid}" =~ ^[0-9]+$ ]] || die "steam_appid required (arg or in profile)"
  mkdir -p "${OVERRIDES_DIR}"
  local out="${OVERRIDES_DIR}/${appid}.env"
  local backend windows retina
  backend="$(profile_get_scalar "${file}" recommended_backend)"
  windows="$(profile_get_scalar "${file}" settings.windows_version)"
  retina="$(profile_get_scalar "${file}" settings.retina)"
  {
    printf '# Generated by profile.command from %s\n' "${file}"
    [[ -n "${backend}" ]] && printf 'COSMOS_BACKEND=%s\n' "${backend}"
    [[ -n "${windows}" ]] && printf 'WINDOWS_VERSION=%s\n' "${windows}"
    [[ "${retina}" == "1" || "${retina}" == "true" ]] && printf 'WINE_RETINA_MODE=1\n'
    local k v
    for k in DXMT_CONFIG STEAM_GAME_ARGS; do
      v="$(profile_get_env_line "${file}" "${k}")"
      [[ -n "${v}" ]] && printf '%s=%s\n' "${k}" "${v}"
    done
  } > "${out}"
  echo "Wrote ${out}"
}

cmd_apply() {
  local file; file="$(resolve_profile "${1:-}")" || die "Profile not found: $1"
  local appid; appid="$(profile_get_scalar "${file}" steam_appid)"
  cmd_export_override "${file}" "${appid}"
  if [[ -x "${SCRIPT_DIR}/repair.command" ]]; then
  local dep fix
  while IFS= read -r dep; do
    [[ -n "${dep}" ]] || continue
    "${SCRIPT_DIR}/repair.command" install-dep "${dep}" || true
  done < <(profile_list_dependencies "${file}")
  while IFS= read -r fix; do
    [[ -n "${fix}" ]] || continue
    "${SCRIPT_DIR}/repair.command" apply-fix "${fix}" || true
  done < <(profile_list_fixes "${file}")
  fi
  log "Profile applied. Re-run detect_steam_games.command to refresh launchers if needed."
}

main() {
  local cmd="${1:-}"; shift || true
  case "${cmd}" in
    list) cmd_list ;;
    show) cmd_show "${1:-}" ;;
    export-override) cmd_export_override "${1:-}" "${2:-}" ;;
    apply) cmd_apply "${1:-}" ;;
    for-appid)
      local appid="${1:-}"; shift
      local pf
      pf="$(profile_find_by_appid "${PROFILES_DIR}" "${appid}")" \
        || die "No profile for steam_appid ${appid}"
      case "${1:-}" in
        show) cmd_show "${pf}" ;;
        apply) cmd_apply "${pf}" ;;
        *) die "Usage: profile.command for-appid <appid> show|apply" ;;
      esac
      ;;
    ""|--help|-h|help) usage ;;
    *) die "Unknown command: ${cmd}" ;;
  esac
}

main "$@"
