#!/usr/bin/env bash
# Registry snapshot + diff helpers (wineregdiff integration).
# Upstream: https://github.com/castaneai/wineregdiff (MIT)

regdiff_snapshots_dir() {
  local base="${COSMOS_SUPPORT_DIR:-$HOME/Library/Application Support/Cosmos}"
  printf '%s/reg-snapshots' "${base}"
}

regdiff_sanitize_label() {
  local label="$1"
  label="$(printf '%s' "${label}" | tr '[:upper:]' '[:lower:]')"
  label="$(printf '%s' "${label}" | sed -E 's/[^a-z0-9._-]+/-/g; s/^-+|-+$//g')"
  [[ -n "${label}" ]] || return 1
  printf '%s' "${label}"
}

regdiff_snapshot_path() {
  local label="$1"
  local safe
  safe="$(regdiff_sanitize_label "${label}")" || return 1
  printf '%s/%s.user.reg' "$(regdiff_snapshots_dir)" "${safe}"
}

regdiff_capture_user_reg() {
  local label="$1"
  local src="${WINEPREFIX:?WINEPREFIX required}/user.reg"
  local dest
  [[ -f "${src}" ]] || {
    echo "No user.reg at ${src}."
    return 1
  }
  dest="$(regdiff_snapshot_path "${label}")" || {
    echo "Invalid snapshot label: ${label}"
    return 1
  }
  mkdir -p "$(dirname "${dest}")"
  cp "${src}" "${dest}"
  echo "Captured ${src} -> ${dest}"
}

regdiff_resolve_reg_file() {
  local arg="$1"
  local path=""
  if [[ -f "${arg}" ]]; then
    path="${arg}"
  else
    path="$(regdiff_snapshot_path "${arg}" 2>/dev/null || true)"
    [[ -f "${path}" ]] || {
      echo "Registry file or snapshot not found: ${arg}" >&2
      return 1
    }
  fi
  printf '%s' "${path}"
}

regdiff_run_diff() {
  local old_file="$1" new_file="$2"
  local root="${REGDIFF_ROOT:-HKCU}"
  if command -v wineregdiff >/dev/null 2>&1; then
    wineregdiff -root "${root}" -force "${old_file}" "${new_file}"
    return 0
  fi
  echo "wineregdiff not found. Install with:" >&2
  echo "  go install github.com/castaneai/wineregdiff/cmd/wineregdiff@latest" >&2
  return 1
}

regdiff_commands_to_recipe() {
  local id="$1" description="$2"
  shift 2
  local cmd line escaped joined=""
  for cmd in "$@"; do
    [[ -n "${cmd}" ]] || continue
    line="$(printf '%s' "${cmd}" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    [[ -n "${line}" ]] || continue
    escaped="${line//\\/\\\\}"
    escaped="${escaped//|/\\|}"
    if [[ -n "${joined}" ]]; then
      joined="${joined}|${escaped}"
    else
      joined="${escaped}"
    fi
  done
  [[ -n "${joined}" ]] || return 1
  cat <<EOF
# Generated by repair.command recipe-from-diff
TYPE=fix
ID=${id}
DESCRIPTION=${description}
ACTION=script
SCRIPT=apply_reg_commands
REG_COMMANDS=${joined}
EOF
}
