#!/usr/bin/env python3
"""Suggest a Cosmos YAML profile draft from community DB + port hints."""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

VALID_STATUS = {
    "platinum",
    "gold",
    "silver",
    "playable",
    "bronze",
    "broken",
    "blocked",
}
VALID_BACKEND = {"recommended", "d3dmetal", "dxmt", "dxvk", "wined3d"}


def slugify(title: str, appid: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    return slug or f"game-{appid}"


def load_json(path: Path) -> dict | None:
    if not path.is_file():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def find_curated_profile(repo: Path, appid: str) -> Path | None:
    steam = repo / "profiles" / "steam"
    if not steam.is_dir():
        return None
    for path in steam.glob("steam-*.yaml"):
        text = path.read_text(encoding="utf-8")
        if re.search(rf"^steam_appid:\s*{appid}\s*$", text, re.M):
            return path
    return None


def protonfix_hints(repo: Path, appid: str) -> dict:
    hint_py = repo / "scripts" / "protonfix_port_hint.py"
    if not hint_py.is_file():
        return {}
    import importlib.util

    spec = importlib.util.spec_from_file_location("protonfix_port_hint", hint_py)
    if spec is None or spec.loader is None:
        return {}
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    resolved, body = mod.fetch_fix(appid)
    if not body:
        return {}
    parsed = mod.parse_fix(body)
    parsed["resolved_fix_file"] = f"{resolved}.py" if resolved else None
    return parsed


def yaml_quote(value: str) -> str:
    if not value or any(c in value for c in ':"\'\n#'):
        return json.dumps(value)
    return value


def build_draft(
    appid: str,
    community: dict | None,
    hints: dict,
    curated: Path | None,
) -> tuple[str, dict]:
    title = (community or {}).get("title") or f"Steam App {appid}"
    status = (community or {}).get("status") or "playable"
    if status not in VALID_STATUS:
        status = "playable"
    backend = (community or {}).get("recommended_backend") or "recommended"
    if backend not in VALID_BACKEND:
        backend = "recommended"
    winver = (community or {}).get("windows_version") or "win10"
    slug = slugify(title, appid)
    profile_id = re.sub(r"[^a-z0-9_]", "_", slug.replace("-", "_"))

    deps = list(hints.get("suggested_dependencies") or [])
    env = dict(hints.get("suggested_env") or {})
    notes_parts: list[str] = []
    if curated:
        notes_parts.append(
            f"Curated profile exists: {curated.relative_to(curated.parents[2])}. "
            "Review diff before merging this draft."
        )
    if community and community.get("notes"):
        notes_parts.append(str(community["notes"]))
    hint_note = hints.get("suggested_notes")
    if hint_note:
        notes_parts.append(str(hint_note))
    if hints.get("resolved_fix_file"):
        notes_parts.append(
            f"Protonfix reference (GPL): {hints['resolved_fix_file']} — port ideas only."
        )
    notes_parts.append("Generated by cosmosdb.command suggest-profile — human review required.")
    notes = " ".join(notes_parts)

    lines = [
        f"# Draft for Steam App ID {appid} — review with ./profile.command validate",
        f"id: {profile_id}",
        f"name: {yaml_quote(title)}",
        "store: steam",
        f"steam_appid: {appid}",
        f"status: {status}",
        f"recommended_backend: {backend}",
        "wine_version: cosmos-stable",
        "settings:",
        "  retina: false",
        f"  windows_version: {winver}",
    ]
    if env:
        lines.append("  env:")
        for key, val in sorted(env.items()):
            lines.append(f"    {key}: {yaml_quote(str(val))}")
    if deps:
        lines.append("dependencies:")
        for dep in deps:
            lines.append(f"  - {dep}")
    lines.append(f"notes: {yaml_quote(notes)}")
    yaml_text = "\n".join(lines) + "\n"
    meta = {
        "steam_appid": int(appid),
        "title": title,
        "status": status,
        "recommended_backend": backend,
        "has_curated_profile": curated is not None,
        "curated_profile": str(curated) if curated else None,
        "community_entry": bool(community),
        "has_protonfix": bool(hints.get("resolved_fix_file")),
    }
    return yaml_text, meta


def main() -> int:
    parser = argparse.ArgumentParser(description="Suggest Cosmos profile draft")
    parser.add_argument("appid", help="Steam App ID")
    parser.add_argument(
        "--repo",
        default=str(Path(__file__).resolve().parents[1]),
        help="Cosmos repo root",
    )
    parser.add_argument(
        "--community-dir",
        default="",
        help="Synced community games directory (default: repo cosmos-db/games)",
    )
    parser.add_argument("--write", action="store_true", help="Write profiles/drafts/")
    parser.add_argument("--json", action="store_true", help="Print metadata JSON only")
    args = parser.parse_args()
    appid = args.appid.strip()
    if not appid.isdigit():
        print("appid must be numeric", file=sys.stderr)
        return 2

    repo = Path(args.repo)
    comm_dir = Path(args.community_dir) if args.community_dir else repo / "cosmos-db" / "games"
    community = load_json(comm_dir / f"{appid}.json")
    curated = find_curated_profile(repo, appid)
    hints = protonfix_hints(repo, appid)
    yaml_text, meta = build_draft(appid, community, hints, curated)

    if args.json:
        print(json.dumps(meta, indent=2))
        return 0

    out_path = repo / "profiles" / "drafts" / f"steam-{appid}-{slugify(meta['title'], appid)}.yaml"
    if args.write:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(yaml_text, encoding="utf-8")
        print(f"Wrote {out_path}")
    else:
        print(yaml_text, end="")
    if curated:
        print(f"\n(existing curated profile: {curated})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
