#!/usr/bin/env bash
# Import winemactricks-json tweaks into Cosmos recipes/.
# Upstream: third_party/winemactricks-json/ (MIT, Alien4042x/winemactricks-json)
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
JSON="${ROOT}/third_party/winemactricks-json/winemactricks.json"
DEPS_DIR="${ROOT}/recipes/dependencies"
FIXES_DIR="${ROOT}/recipes/fixes"
SYNC=0 FORCE=0 DRY_RUN=0

usage() {
  cat <<'EOF'
Import winemactricks-json tweaks into Cosmos recipe files.

Usage: scripts/import_winemactricks.sh [options]

Options:
  --sync     Download latest winemactricks.json from GitHub before import.
  --force    Overwrite existing generated recipes.
  --dry-run  Print actions without writing files.
  -h, --help Show this help.

Generated fix recipes are marked with SOURCE=winemactricks:<id> in the header.
EOF
}

while (($#)); do
  case "$1" in
    --sync) SYNC=1; shift ;;
    --force) FORCE=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1" >&2; usage >&2; exit 1 ;;
  esac
done

if (( SYNC )); then
  echo "Syncing ${JSON} from upstream..."
  curl -fsSL \
    "https://raw.githubusercontent.com/Alien4042x/winemactricks-json/main/winemactricks.json" \
    -o "${JSON}"
fi

[[ -f "${JSON}" ]] || { echo "Missing ${JSON}" >&2; exit 1; }
command -v python3 >/dev/null 2>&1 || { echo "python3 required" >&2; exit 1; }

python3 - "${JSON}" "${DEPS_DIR}" "${FIXES_DIR}" "${FORCE}" "${DRY_RUN}" <<'PY'
import json
import re
import sys
from pathlib import Path

json_path, deps_dir, fixes_dir, force_s, dry_s = sys.argv[1:6]
force = force_s == "1"
dry = dry_s == "1"

data = json.loads(Path(json_path).read_text(encoding="utf-8"))
tweaks = data.get("tweaks") or []

MODE_MAP = {
    "native": "n",
    "builtin": "b",
    "disabled": "d",
    "empty": "e",
    "n": "n",
    "b": "b",
    "d": "d",
    "e": "e",
}

def slugify(tweak_id: str) -> str:
    s = tweak_id.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")

def dll_entries(tweak: dict) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for item in tweak.get("files") or []:
        dll = item.get("dll")
        mode = item.get("mode")
        if dll and mode:
            flag = MODE_MAP.get(str(mode).lower())
            if flag:
                out.append((dll.replace(".dll", ""), flag))
    for action in tweak.get("actions") or []:
        if action.get("type") == "reg_override":
            dll = action.get("dll")
            mode = action.get("mode")
            if dll and mode:
                flag = MODE_MAP.get(str(mode).lower())
                if flag:
                    out.append((dll.replace(".dll", ""), flag))
    # dedupe preserving order
    seen = set()
    deduped = []
    for dll, flag in out:
        key = (dll, flag)
        if key not in seen:
            seen.add(key)
            deduped.append(key)
    return deduped

def has_copy_actions(tweak: dict) -> bool:
    for action in tweak.get("actions") or []:
        if action.get("type") in ("copy_dll", "download"):
            return True
    for item in tweak.get("files") or []:
        if item.get("source_url") or item.get("destination"):
            if not item.get("dll"):
                return True
    return False

def write_recipe(path: Path, lines: list[str]) -> None:
    body = "\n".join(lines) + "\n"
    if dry:
        print(f"would write {path}")
        print(body)
        return
    path.write_text(body, encoding="utf-8")
    print(f"wrote {path}")

created = skipped = unsupported = 0

for tweak in tweaks:
    tid = tweak.get("id") or ""
    if not tid:
        continue
    title = (tweak.get("title") or tid).replace("\n", " ").strip()
    desc = title
    if tweak.get("description"):
        desc = f"{title} — {tweak['description']}".strip()

    wt = tweak.get("winetricks")
    if wt:
        rid = slugify(tid)
        path = Path(deps_dir) / f"{rid}.recipe"
        if path.exists() and not force:
            existing = path.read_text(encoding="utf-8")
            if "SOURCE=winemactricks:" not in existing:
                print(f"skip dep {rid}: hand-written recipe exists")
                skipped += 1
                continue
        lines = [
            "# Generated by scripts/import_winemactricks.sh — do not edit by hand",
            f"SOURCE=winemactricks:{tid}",
            "TYPE=dependency",
            f"ID={rid}",
            f"DESCRIPTION={desc} (winemactricks)",
            f"WINETRICKS={wt}",
        ]
        write_recipe(path, lines)
        created += 1
        continue

    if has_copy_actions(tweak):
        print(f"skip {tid}: copy/download actions not yet supported by Cosmos import")
        unsupported += 1
        continue

    dlls = dll_entries(tweak)
    if not dlls:
        print(f"skip {tid}: no supported dll/reg_override entries")
        unsupported += 1
        continue

    override = ";".join(f"{dll}={flag}" for dll, flag in dlls)
    rid = slugify(tid)
    path = Path(fixes_dir) / f"{rid}.recipe"
    if path.exists() and not force:
        existing = path.read_text(encoding="utf-8")
        if "SOURCE=winemactricks:" not in existing:
            print(f"skip fix {rid}: hand-written recipe exists")
            skipped += 1
            continue
    lines = [
        "# Generated by scripts/import_winemactricks.sh — do not edit by hand",
        f"SOURCE=winemactricks:{tid}",
        "TYPE=fix",
        f"ID={rid}",
        f"DESCRIPTION={desc} (winemactricks)",
        "ACTION=script",
        "SCRIPT=dll_override",
        f"DLL_OVERRIDE={override}",
    ]
    write_recipe(path, lines)
    created += 1

print(f"import complete: created={created} skipped={skipped} unsupported={unsupported}")
PY
